language: generic
sudo: required
services: docker
env:
  global:
  - PROJECT_NAME=lpp-feedback
  - PROJECT_VERSION=1.0.0
  - DOCKER_USERNAME=bezpov
  - secure: bWY0MNxRHUch72ul6iwDDzecuf4SUVWb0ZlYIQtg+Y14UE11YsFhSE8IpOYHVoZRosvPhz7gx/9By8YxPwZmNufiFjrDjjoXf9ZRdbIoz+vhDw14nQuUmaDOWqtnVjA4IzM0lI9nwgzry5s+XSAPUb6oaNFHgHjI7JdsLmeCQyxxxI/MnDdmzulc+G7zjwdnyLqjOHJ0iDjHY3iowcUPM/wAoebv7fTpSitqok6e/jLZ/9xcZmACdOAekCZGAxOQCzYT5o269RQGt8RctQn2177Yq75u4Jiu2g43MEtieZnI5a6sXoTtdxG+kAyCLUcBkThvYT+JN1oJHDdX+kJ5wJLWwbVSUsJtJbwH/U/f68fyjk7zRqkwGimgBLaiaQpf3JDFGoJjCIdOyFw4MtEPrpz5EWvf5w401Nq1VcXMMjcUbZEAFcuIMLFLFhriQvACWdpGTob/eWT60YfRMuD/fsxdD3lcHYtZjTcmi3vuFIQ1/TZuCZylQz9iFD5ez29OwHaUxHIMaJT4ypMf6X/Thn2CseZqUM8xZxO/mu309l3R5g2np04vTpLXSUX9Zy0LEkVfaOmlNrLrbICVmbw8FR/tyeWYjkd0hvFV/wX3Z1xc6kSYbJ+WAmuGSXdh7pLRcWWAM/+uIBcenh9BzTB7fEMCw18dMAI1NOhkWe0636o=
before_install:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker image build -t $PROJECT_NAME:$PROJECT_VERSION .
- docker image tag $PROJECT_NAME:$PROJECT_VERSION $DOCKER_USERNAME/$PROJECT_NAME:$PROJECT_VERSION
- docker image push $DOCKER_USERNAME/$PROJECT_NAME
