apiVersion: apps/v1
kind: Deployment
metadata:
  name: lpp-feedback
spec:
  selector:
    matchLabels:
      app: lpp-feedback
  replicas: 1
  template:
    metadata:
      labels:
        app: lpp-feedback
    spec:
      containers:
        - image: bezpov/lpp-feedback:1.0.6
          name: lpp-feedback-container
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 3
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: lpp-feedback-service
  namespace: default
  labels:
    app: lpp-feedback
spec:
  ports:
    - protocol: TCP
      port: 82
      targetPort: 8080
  selector:
    app: lpp-feedback
  type: NodePort